name: Build and Deploy JAR

# Trigger process to push into main branch
on:
  push:
    branches:
      - main  # Project main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Update DB url
        run: sed -i 's|<db_url>|${{ secrets.DB_URL }}|' src/main/resources/application-prod.properties

      - name: Update DB username
        run: sed -i 's|<db_username>|${{ secrets.DB_USERNAME }}|' src/main/resources/application-prod.properties

      - name: Update DB password
        run: sed -i 's|<db_password>|${{ secrets.DB_PASSWORD }}|' src/main/resources/application-prod.properties

      - name: Update key store
        run: sed -i 's|<key_store>|${{ secrets.KEY_STORE }}|' src/main/resources/application-prod.properties

      - name: Update key store password
        run: sed -i 's|<key_store_password>|${{ secrets.KEY_STORE_PASSWORD }}|' src/main/resources/application-prod.properties

      - name: Update key store type
        run: sed -i 's|<key_store_type>|${{ secrets.KEY_STORE_TYPE }}|' src/main/resources/application-prod.properties

      - name: Update key store alias
        run: sed -i 's|<key_store_alias>|${{ secrets.KEY_STORE_ALIAS }}|' src/main/resources/application-prod.properties

      - name: Update jwt private key
        run: sed -i 's|<jwt_private_key>|${{ secrets.JWT_PRIVATE_KEY }}|' src/main/resources/application-prod.properties

      - name: Update master username
        run: sed -i 's|<master_username>|${{ secrets.MASTER_USERNAME }}|' src/main/resources/application-prod.properties

      - name: Update master password
        run: sed -i 's|<master_password>|${{ secrets.MASTER_PASSWORD }}|' src/main/resources/application-prod.properties

      - name: Update cloud region
        run: sed -i 's|<cloud_region>|${{ secrets.CLOUD_REGION }}|' src/main/resources/application-prod.properties

      - name: Update cloud endpoint
        run: sed -i 's|<cloud_endpoint>|${{ secrets.CLOUD_ENDPOINT }}|' src/main/resources/application-prod.properties

      - name: Update cloud cdn
        run: sed -i 's|<cloud_cdn>|${{ secrets.CLOUD_CDN }}|' src/main/resources/application-prod.properties

      - name: Update cloud bucket name
        run: sed -i 's|<cloud_bucket_name>|${{ secrets.CLOUD_BUCKET_NAME }}|' src/main/resources/application-prod.properties

      - name: Update cloud access key
        run: sed -i 's|<cloud_access_key>|${{ secrets.CLOUD_ACCESS_KEY }}|' src/main/resources/application-prod.properties

      - name: Update cloud secret key
        run: sed -i 's|<cloud_secret_key>|${{ secrets.CLOUD_SECRET_KEY }}|' src/main/resources/application-prod.properties

      # Build Maven project
      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true

      # Setup SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_ed25519

      # Add server to known_hosts
      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts  # Убедитесь, что файл имеет правильные разрешения

      # Add SSH key for SCP
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      # Send JAR into server via SCP
      - name: Copy JAR to server via SCP
        run: scp target/yamaneko_back_end-0.0.1-SNAPSHOT.jar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/yamaneko
        env:
          # Using secrets
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}